import { ChainInfo } from "@keplr-wallet/types";
import { Bech32Address } from "@keplr-wallet/cosmos";
import { TOKEN_CURRENCIES } from "./tokenCurrencies";

export interface EmbedChainInfo extends ChainInfo {
  gasPriceStep?: {
    low: number;
    average: number;
    high: number;
  };
}

export const CHAIN_IDS = {
  CosmosHub: "cosmoshub-4",
  Osmosis: "osmosis-1",
  Secret: "secret-4",
  Regen: "regen-1",
  Akash: "akashnet-2",
  SifChain: "sifchain-1",
  Stargaze: "stargaze-1",
  Sentinel: "sentinelhub-2",
  Persistence: "core-1",
  Kava: "kava_2222-10",
  CRO: "crypto-org-chain-mainnet-1",
  Iris: "irishub-1",
  Agoric: "agoric-3",
  Axelar: "axelar-dojo-1",
  Certic: "shentu-2.2",
  Ixo: "impacthub-3",
  Emoney: "emoney-3",
  Juno: "juno-1",
  Sommelier: "sommelier-3",
  Umee: "umee-1",
  Evmos: "evmos_9001-2",
  Bostrom: "bostrom",
  Starname: "iov-mainnet-ibc",
  Gravity: "gravity-bridge-3",
  Stride: "stride-1",
} as const;

export const CHAIN_NAMES = {
  CosmosHub: "Cosmos Hub",
  Osmosis: "Osmosis",
  Secret: "Secret Network",
  Regen: "Regen",
  Akash: "Akash",
  SifChain: "SifChain",
  Stargaze: "Stargaze",
  Sentinel: "Sentinel",
  Persistence: "Persistence",
  Kava: "Kava",
  CRO: "Crypto.org",
  Iris: "IRISnet",
  Agoric: "Agoric",
  Axelar: "Axelar",
  Certic: "Certik",
  Ixo: "ixo",
  Emoney: "e-Money",
  Juno: "Juno",
  Sommelier: "Sommelier",
  Umee: "Umee",
  Evmos: "Evmos",
  Bostrom: "Bostrom",
  Starname: "Starname",
  Gravity: "Gravity Bridge",
  Stride: "Stride",
  MarsProtocol: "Mars Protocol",
} as const;

export const EMBED_CHAIN_INFOS: EmbedChainInfo[] = [
  {
    rpc: "https://rpc-cosmoshub.keplr.app",
    rest: "https://lcd-cosmoshub.keplr.app",
    chainId: CHAIN_IDS.CosmosHub,
    chainName: CHAIN_NAMES.CosmosHub,
    stakeCurrency: TOKEN_CURRENCIES.ATOM,
    bip44: {
      coinType: 118,
    },
    bech32Config: Bech32Address.defaultBech32Config("cosmos"),
    currencies: [TOKEN_CURRENCIES.ATOM],
    feeCurrencies: [TOKEN_CURRENCIES.ATOM],
    gasPriceStep: {
      low: 0.01,
      average: 0.025,
      high: 0.04,
    },
    features: ["ibc-transfer", "ibc-go"],
  },
  {
    rpc: "https://rpc-osmosis.keplr.app",
    rest: "https://lcd-osmosis.keplr.app",
    chainId: CHAIN_IDS.Osmosis,
    chainName: CHAIN_NAMES.Osmosis,
    stakeCurrency: TOKEN_CURRENCIES.OSMO,
    bip44: {
      coinType: 118,
    },
    bech32Config: Bech32Address.defaultBech32Config("osmo"),
    currencies: [TOKEN_CURRENCIES.OSMO, TOKEN_CURRENCIES.ION],
    feeCurrencies: [TOKEN_CURRENCIES.OSMO],
    gasPriceStep: {
      low: 0,
      average: 0.025,
      high: 0.04,
    },
    features: ["ibc-transfer", "ibc-go", "cosmwasm"],
  },
  {
    rpc: "https://rpc-secret.keplr.app",
    rest: "https://lcd-secret.keplr.app",
    chainId: CHAIN_IDS.Secret,
    chainName: CHAIN_NAMES.Secret,
    stakeCurrency: TOKEN_CURRENCIES.SCRT,
    bip44: {
      coinType: 529,
    },
    alternativeBIP44s: [
      {
        coinType: 118,
      },
    ],
    bech32Config: Bech32Address.defaultBech32Config("secret"),
    currencies: [TOKEN_CURRENCIES.SCRT],
    feeCurrencies: [TOKEN_CURRENCIES.SCRT],
    gasPriceStep: {
      low: 0.0125,
      average: 0.1,
      high: 0.25,
    },
    features: ["secretwasm", "ibc-go", "ibc-transfer"],
  },
  {
    rpc: "https://rpc-regen.keplr.app",
    rest: "https://lcd-regen.keplr.app",
    chainId: CHAIN_IDS.Regen,
    chainName: CHAIN_NAMES.Regen,
    stakeCurrency: TOKEN_CURRENCIES.REGEN,
    bip44: { coinType: 118 },
    bech32Config: Bech32Address.defaultBech32Config("regen"),
    currencies: [TOKEN_CURRENCIES.REGEN],
    feeCurrencies: [TOKEN_CURRENCIES.REGEN],
    gasPriceStep: {
      low: 0.015,
      average: 0.025,
      high: 0.04,
    },
    features: ["ibc-transfer", "ibc-go"],
  },
  {
    rpc: "https://rpc-akash.keplr.app",
    rest: "https://lcd-akash.keplr.app",
    chainId: CHAIN_IDS.Akash,
    chainName: CHAIN_NAMES.Akash,
    stakeCurrency: TOKEN_CURRENCIES.AKT,
    bip44: {
      coinType: 118,
    },
    bech32Config: Bech32Address.defaultBech32Config("akash"),
    currencies: [TOKEN_CURRENCIES.AKT],
    feeCurrencies: [TOKEN_CURRENCIES.AKT],
    gasPriceStep: {
      low: 0.01,
      average: 0.025,
      high: 0.04,
    },
    features: ["ibc-transfer"],
  },
  {
    rpc: "https://rpc-sifchain.keplr.app",
    rest: "https://lcd-sifchain.keplr.app",
    chainId: CHAIN_IDS.SifChain,
    chainName: CHAIN_NAMES.SifChain,
    stakeCurrency: TOKEN_CURRENCIES.ROWAN,
    bip44: {
      coinType: 118,
    },
    bech32Config: Bech32Address.defaultBech32Config("sif"),
    currencies: [TOKEN_CURRENCIES.ROWAN],
    feeCurrencies: [TOKEN_CURRENCIES.ROWAN],
    gasPriceStep: {
      low: 1000000000000,
      average: 1500000000000,
      high: 2000000000000,
    },
    features: [],
  },
  {
    rpc: "https://rpc-stargaze.keplr.app",
    rest: "https://lcd-stargaze.keplr.app",
    chainId: CHAIN_IDS.Stargaze,
    chainName: CHAIN_NAMES.Stargaze,
    stakeCurrency: TOKEN_CURRENCIES.STARS,
    bip44: {
      coinType: 118,
    },
    bech32Config: Bech32Address.defaultBech32Config("stars"),
    currencies: [TOKEN_CURRENCIES.STARS],
    feeCurrencies: [TOKEN_CURRENCIES.STARS],
    gasPriceStep: {
      low: 0.01,
      average: 0.025,
      high: 0.04,
    },
    features: ["ibc-transfer", "ibc-go", "cosmwasm", "wasmd_0.24+"],
  },
  {
    rpc: "https://rpc-sentinel.keplr.app",
    rest: "https://lcd-sentinel.keplr.app",
    chainId: CHAIN_IDS.Sentinel,
    chainName: CHAIN_NAMES.Sentinel,
    stakeCurrency: TOKEN_CURRENCIES.DVPN,
    bip44: { coinType: 118 },
    bech32Config: Bech32Address.defaultBech32Config("sent"),
    currencies: [TOKEN_CURRENCIES.DVPN],
    feeCurrencies: [TOKEN_CURRENCIES.DVPN],
    gasPriceStep: {
      low: 0.1,
      average: 0.25,
      high: 0.4,
    },
    features: ["ibc-transfer"],
  },
  {
    rpc: "https://rpc-persistence.keplr.app",
    rest: "https://lcd-persistence.keplr.app",
    chainId: CHAIN_IDS.Persistence,
    chainName: CHAIN_NAMES.Persistence,
    stakeCurrency: TOKEN_CURRENCIES.XPRT,
    bip44: {
      coinType: 750,
    },
    bech32Config: Bech32Address.defaultBech32Config("persistence"),
    currencies: [TOKEN_CURRENCIES.XPRT],
    feeCurrencies: [TOKEN_CURRENCIES.XPRT],
    gasPriceStep: {
      low: 0,
      average: 0.025,
      high: 0.04,
    },
    features: ["ibc-transfer", "ibc-go"],
  },
  {
    rpc: "https://rpc-kava.keplr.app",
    rest: "https://lcd-kava.keplr.app",
    chainId: CHAIN_IDS.Kava,
    chainName: CHAIN_NAMES.Kava,
    stakeCurrency: TOKEN_CURRENCIES.KAVA,
    bip44: {
      coinType: 459,
    },
    alternativeBIP44s: [{ coinType: 118 }],
    bech32Config: Bech32Address.defaultBech32Config("kava"),
    currencies: [TOKEN_CURRENCIES.KAVA],
    feeCurrencies: [TOKEN_CURRENCIES.KAVA],
    gasPriceStep: {
      low: 0.05,
      average: 0.1,
      high: 0.25,
    },
  },
  {
    rpc: "https://rpc-crypto-org.keplr.app",
    rest: "https://lcd-crypto-org.keplr.app",
    chainId: CHAIN_IDS.CRO,
    chainName: CHAIN_NAMES.CRO,
    stakeCurrency: TOKEN_CURRENCIES.CRO,
    bip44: {
      coinType: 394,
    },
    bech32Config: {
      bech32PrefixAccAddr: "cro",
      bech32PrefixAccPub: "cropub",
      bech32PrefixValAddr: "crocncl",
      bech32PrefixValPub: "crocnclpub",
      bech32PrefixConsAddr: "crocnclcons",
      bech32PrefixConsPub: "crocnclconspub",
    },
    currencies: [TOKEN_CURRENCIES.CRO],
    feeCurrencies: [TOKEN_CURRENCIES.CRO],
    gasPriceStep: {
      low: 0.025,
      average: 0.03,
      high: 0.04,
    },
    features: ["ibc-transfer"],
  },
  {
    rpc: "https://rpc-iris.keplr.app",
    rest: "https://lcd-iris.keplr.app",
    chainId: CHAIN_IDS.Iris,
    chainName: CHAIN_NAMES.Iris,
    stakeCurrency: TOKEN_CURRENCIES.IRIS,
    bip44: { coinType: 566 },
    bech32Config: {
      bech32PrefixAccAddr: "iaa",
      bech32PrefixAccPub: "iap",
      bech32PrefixValAddr: "iva",
      bech32PrefixValPub: "ivp",
      bech32PrefixConsAddr: "ica",
      bech32PrefixConsPub: "icp",
    },
    currencies: [TOKEN_CURRENCIES.IRIS],
    feeCurrencies: [TOKEN_CURRENCIES.IRIS],
    gasPriceStep: {
      low: 0.2,
      average: 0.3,
      high: 0.4,
    },
    features: [],
  },
  {
    rpc: "https://rpc-agoric.keplr.app",
    rest: "https://lcd-agoric.keplr.app",
    chainId: CHAIN_IDS.Agoric,
    chainName: CHAIN_NAMES.Agoric,
    stakeCurrency: TOKEN_CURRENCIES.BLD,
    bip44: {
      coinType: 564,
    },
    bech32Config: Bech32Address.defaultBech32Config("agoric"),
    currencies: [TOKEN_CURRENCIES.BLD, TOKEN_CURRENCIES.RUN],
    feeCurrencies: [TOKEN_CURRENCIES.BLD],
    gasPriceStep: {
      low: 0,
      average: 0,
      high: 0,
    },
    features: ["ibc-go"],
  },
  {
    rpc: "https://rpc-axelar.keplr.app",
    rest: "https://lcd-axelar.keplr.app",
    chainId: CHAIN_IDS.Axelar,
    chainName: CHAIN_NAMES.Axelar,
    stakeCurrency: TOKEN_CURRENCIES.AXL,
    bip44: {
      coinType: 118,
    },
    bech32Config: Bech32Address.defaultBech32Config("axelar"),
    currencies: [
      TOKEN_CURRENCIES.AXL,
      TOKEN_CURRENCIES.USDC,
      TOKEN_CURRENCIES.FRAX,
      TOKEN_CURRENCIES.USDT,
      TOKEN_CURRENCIES.DAI,
      TOKEN_CURRENCIES.WETH,
      TOKEN_CURRENCIES.WBTC,
      TOKEN_CURRENCIES.LINK,
      TOKEN_CURRENCIES.AAVE,
      TOKEN_CURRENCIES.APE,
      TOKEN_CURRENCIES.AXS,
      TOKEN_CURRENCIES.MKR,
      TOKEN_CURRENCIES.RAI,
      TOKEN_CURRENCIES.SHIB,
      TOKEN_CURRENCIES.stETH,
      TOKEN_CURRENCIES.UNI,
      TOKEN_CURRENCIES.XCN,
      TOKEN_CURRENCIES.WGLMR,
      TOKEN_CURRENCIES.DOT,
    ],
    feeCurrencies: [TOKEN_CURRENCIES.AXL],
    gasPriceStep: {
      low: 0.05,
      average: 0.075,
      high: 0.1,
    },
    features: ["ibc-transfer", "ibc-go"],
  },
  {
    rpc: "https://rpc-certik.keplr.app",
    rest: "https://lcd-certik.keplr.app",
    chainId: CHAIN_IDS.Certic,
    chainName: CHAIN_NAMES.Certic,
    stakeCurrency: TOKEN_CURRENCIES.CTK,
    bip44: { coinType: 118 },
    bech32Config: Bech32Address.defaultBech32Config("certik"),
    currencies: [TOKEN_CURRENCIES.CTK],
    feeCurrencies: [TOKEN_CURRENCIES.CTK],
    gasPriceStep: {
      low: 0.01,
      average: 0.025,
      high: 0.04,
    },
    features: [],
  },
  {
    rpc: "https://rpc-impacthub.keplr.app",
    rest: "https://lcd-impacthub.keplr.app",
    chainId: CHAIN_IDS.Ixo,
    chainName: CHAIN_NAMES.Ixo,
    stakeCurrency: TOKEN_CURRENCIES.IXO,
    bip44: {
      coinType: 118,
    },
    bech32Config: Bech32Address.defaultBech32Config("ixo"),
    currencies: [TOKEN_CURRENCIES.IXO],
    feeCurrencies: [TOKEN_CURRENCIES.IXO],
    gasPriceStep: {
      low: 0.01,
      average: 0.025,
      high: 0.04,
    },
    features: ["ibc-transfer"],
  },
  {
    rpc: "https://rpc-emoney.keplr.app",
    rest: "https://lcd-emoney.keplr.app",
    chainId: CHAIN_IDS.Emoney,
    chainName: CHAIN_NAMES.Emoney,
    stakeCurrency: TOKEN_CURRENCIES.NGM,
    bip44: {
      coinType: 118,
    },
    bech32Config: Bech32Address.defaultBech32Config("emoney"),
    currencies: [TOKEN_CURRENCIES.NGM, TOKEN_CURRENCIES.EEUR],
    feeCurrencies: [TOKEN_CURRENCIES.NGM],
    gasPriceStep: {
      low: 1,
      average: 1,
      high: 1,
    },
    features: ["ibc-transfer"],
  },
  {
    rpc: "https://rpc-juno.keplr.app",
    rest: "https://lcd-juno.keplr.app",
    chainId: CHAIN_IDS.Juno,
    chainName: CHAIN_NAMES.Juno,
    stakeCurrency: TOKEN_CURRENCIES.JUNO,
    bip44: {
      coinType: 118,
    },
    bech32Config: Bech32Address.defaultBech32Config("juno"),
    currencies: [
      TOKEN_CURRENCIES.JUNO,
      TOKEN_CURRENCIES.NETA,
      TOKEN_CURRENCIES.MARBLE,
      TOKEN_CURRENCIES.HOPE,
      TOKEN_CURRENCIES.RAC,
      TOKEN_CURRENCIES.BLOCK,
      TOKEN_CURRENCIES.DHK,
      TOKEN_CURRENCIES.RAW,
      TOKEN_CURRENCIES.ASVT,
      TOKEN_CURRENCIES.JOE,
    ],
    feeCurrencies: [TOKEN_CURRENCIES.JUNO],
    gasPriceStep: {
      low: 0.001,
      average: 0.0025,
      high: 0.004,
    },
    features: ["ibc-transfer", "ibc-go", "cosmwasm", "wasmd_0.24+"],
  },
  {
    rpc: "https://rpc-sommelier.keplr.app",
    rest: "https://lcd-sommelier.keplr.app",
    chainId: CHAIN_IDS.Sommelier,
    chainName: CHAIN_NAMES.Sommelier,
    stakeCurrency: TOKEN_CURRENCIES.SOMM,
    bip44: {
      coinType: 118,
    },
    bech32Config: Bech32Address.defaultBech32Config("somm"),
    currencies: [TOKEN_CURRENCIES.SOMM],
    feeCurrencies: [TOKEN_CURRENCIES.SOMM],
    features: ["ibc-transfer", "ibc-go"],
  },
  {
    rpc: "https://rpc-umee.keplr.app",
    rest: "https://lcd-umee.keplr.app",
    chainId: CHAIN_IDS.Umee,
    chainName: CHAIN_NAMES.Umee,
    stakeCurrency: TOKEN_CURRENCIES.UMEE,
    bip44: {
      coinType: 118,
    },
    bech32Config: Bech32Address.defaultBech32Config("umee"),
    currencies: [TOKEN_CURRENCIES.UMEE],
    feeCurrencies: [TOKEN_CURRENCIES.UMEE],
    gasPriceStep: {
      low: 0,
      average: 0.025,
      high: 0.04,
    },
    features: ["ibc-transfer", "ibc-go"],
  },
  {
    rpc: "https://rpc-evmos.keplr.app",
    rest: "https://lcd-evmos.keplr.app",
    chainId: CHAIN_IDS.Evmos,
    chainName: CHAIN_NAMES.Evmos,
    stakeCurrency: TOKEN_CURRENCIES.EVMOS,
    bip44: {
      coinType: 60,
    },
    bech32Config: Bech32Address.defaultBech32Config("evmos"),
    currencies: [TOKEN_CURRENCIES.EVMOS],
    feeCurrencies: [TOKEN_CURRENCIES.EVMOS],
    gasPriceStep: {
      low: 25000000000,
      average: 25000000000,
      high: 40000000000,
    },
    features: ["ibc-transfer", "ibc-go", "eth-address-gen", "eth-key-sign"],
  },
  {
    rpc: "https://rpc-cyber.keplr.app",
    rest: "https://lcd-cyber.keplr.app",
    chainId: CHAIN_IDS.Bostrom,
    chainName: CHAIN_NAMES.Bostrom,
    stakeCurrency: TOKEN_CURRENCIES.BOOT,
    bip44: { coinType: 118 },
    bech32Config: Bech32Address.defaultBech32Config("bostrom"),
    currencies: [
      TOKEN_CURRENCIES.BOOT,
      TOKEN_CURRENCIES.H,
      TOKEN_CURRENCIES.V,
      TOKEN_CURRENCIES.A,
      TOKEN_CURRENCIES.TOCYB,
    ],
    feeCurrencies: [TOKEN_CURRENCIES.BOOT],
    gasPriceStep: {
      low: 0,
      average: 0,
      high: 0.01,
    },
    features: ["ibc-transfer", "cosmwasm"],
  },
  {
    rpc: "https://rpc-iov.keplr.app",
    rest: "https://lcd-iov.keplr.app",
    chainId: CHAIN_IDS.Starname,
    chainName: CHAIN_NAMES.Starname,
    stakeCurrency: TOKEN_CURRENCIES.IOV,
    bip44: {
      coinType: 234,
    },
    bech32Config: Bech32Address.defaultBech32Config("star"),
    currencies: [TOKEN_CURRENCIES.IOV],
    feeCurrencies: [TOKEN_CURRENCIES.IOV],
    gasPriceStep: {
      low: 1,
      average: 2,
      high: 3,
    },
    features: ["ibc-transfer", "cosmwasm", "ibc-go"],
  },
  {
    rpc: "https://rpc-gravity-bridge.keplr.app",
    rest: "https://lcd-gravity-bridge.keplr.app",
    chainId: CHAIN_IDS.Gravity,
    chainName: CHAIN_NAMES.Gravity,
    stakeCurrency: TOKEN_CURRENCIES.GRAV,
    bip44: {
      coinType: 118,
    },
    bech32Config: Bech32Address.defaultBech32Config("gravity"),
    currencies: [
      TOKEN_CURRENCIES.GRAV,
      TOKEN_CURRENCIES.PSTAKE,
      TOKEN_CURRENCIES.GWBTC,
      TOKEN_CURRENCIES.GWETH,
      TOKEN_CURRENCIES.GUSDC,
      TOKEN_CURRENCIES.GDAI,
      TOKEN_CURRENCIES.GUSDT,
    ],
    feeCurrencies: [TOKEN_CURRENCIES.GRAV],
    gasPriceStep: {
      low: 0.01,
      average: 0.025,
      high: 0.04,
    },
    features: ["cosmwasm", "ibc-transfer", "ibc-go", "wasmd_0.24+"],
  },
  {
    rpc: "https://rpc-stride.keplr.app",
    rest: "https://lcd-stride.keplr.app",
    chainId: CHAIN_IDS.Stride,
    chainName: CHAIN_NAMES.Stride,
    stakeCurrency: TOKEN_CURRENCIES.STRD,
    bip44: {
      coinType: 118,
    },
    bech32Config: Bech32Address.defaultBech32Config("stride"),
    currencies: [TOKEN_CURRENCIES.STRD],
    feeCurrencies: [TOKEN_CURRENCIES.STRD],
    gasPriceStep: {
      low: 0,
      average: 0,
      high: 0.04,
    },
    features: ["ibc-transfer", "ibc-go"],
  },
];
